SOURCE := main.cpp Fixed.cpp

NAME := towards_a_more_useful_fixed_point_number_class

all: $(NAME)

$(NAME): $(SOURCE)
	c++ -Wall -Wextra -Werror -std=c++98 $(SOURCE) -o $(NAME)

clean:

fclean: clean
	rm -f $(NAME)

re: fclean all
