SOURCE := main.cpp Fixed.cpp

NAME := my_first_class_in_orthodox_canonical_form

all: $(NAME)

$(NAME): $(SOURCE)
	c++ -Wall -Wextra -Werror -std=c++98 $(SOURCE) -o $(NAME)

clean:

fclean: clean
	rm -f $(NAME)

re: fclean all
